### One Hot Encoding

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
# Sample categorical data
data = np.array([['Red'], ['Green'], ['Blue'], ['Red'], ['Blue']])
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(data)

In [2]:
encoded_data

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

# Bag of Words (BoW) Example

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    "text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]
})

In [5]:
df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bow = cv.fit_transform(df['text'])

In [7]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [9]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [10]:
# Show feature names (the actual words in the vocabulary)
print("\nFeature Names (columns):")
print(cv.get_feature_names_out())


Feature Names (columns):
['comment' 'dswithbappy' 'people' 'watch' 'write']


# N grams

In [11]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})
df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [12]:
# BI grams
cv = CountVectorizer(ngram_range=(2, 2))

In [13]:
bow = cv.fit_transform(df['text'])

In [14]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [15]:
#vocabulary
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [16]:
#Tri grams
cv = CountVectorizer(ngram_range=(3, 3))
bow = cv.fit_transform(df['text'])

In [17]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [18]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


# TF-IDF (Term frequency- Inverse document frequency

In [19]:
f = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()


In [21]:
arr = tfidf_vectorizer.fit_transform(df['text']).toarray()

In [22]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

# Word2vec 
### is a popular word embedding technique that represents words as dense vectors in a continuous vector space. It captures semantic relationships between words based on their co-occurrence in a large corpus of text. The two main architectures for Word2vec are Continuous Bag of Words (CBOW) and Skip-gram. CBOW predicts a target word based on its context, while Skip-gram predicts the context given a target word. Word2vec is widely used in natural language processing tasks to capture the meaning and relationships between words.

In [23]:
import pandas as pd 
import numpy as np
import gensim
import os

In [24]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /Users/al-amen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/al-
[nltk_data]     amen/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [25]:
story = []
for filename in os.listdir('../Day-4'):
    if filename.endswith('.ipynb'):
        pass
    f = open(os.path.join('../Day-4', filename))
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [26]:
story

[['cells',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'one',
  'hot',
  'encoding',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'cd',
  'metadata',
  'outputs',
  'source',
  'from',
  'sklearn',
  'preprocessing',
  'import',
  'onehotencoder',
  'import',
  'numpy',
  'as',
  'np',
  'sample',
  'categorical',
  'data',
  'data',
  'np',
  'array',
  'red',
  'green',
  'blue',
  'red',
  'blue',
  'encoder',
  'onehotencoder',
  'sparse_output',
  'false',
  'encoded_data',
  'encoder',
  'fit_transform',
  'data',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'ba',
  'metadata',
  'outputs',
  'data',
  'text',
  'plain',
  'array'],
 [],
 [],
 [],
 [],
 ['execution_count',
  'metadata',
  'output_type',
  'execute_result',
  'source',
  'encoded_data',
  'cell_type',
  'markdown',
  'id',
  'metadata',
  'source',
  'bag',
  'of',
  'words',
  'bow',
  'example',
  'cell_type',
  'code',
  'execution_count',
  'id',
  'metadata',
  'outp

In [27]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [28]:
model.build_vocab(story)

In [29]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(232452, 328875)

In [30]:
vec = model.wv.get_normed_vectors()

In [31]:
vec

array([[ 0.02517939,  0.10539257, -0.01789836, ..., -0.25972202,
         0.02362148, -0.03879691],
       [ 0.0198248 ,  0.10579091, -0.0211808 , ..., -0.25914615,
         0.03031425, -0.04337778],
       [ 0.0210031 ,  0.11112093, -0.02475179, ..., -0.2584012 ,
         0.03695344, -0.0495365 ],
       ...,
       [-0.02532568,  0.10550658, -0.03180919, ..., -0.2131351 ,
         0.10557029, -0.04641702],
       [ 0.00483298,  0.10203088, -0.03174058, ..., -0.2283772 ,
         0.11749382, -0.06444091],
       [-0.17748323, -0.07884622,  0.00881228, ...,  0.07569203,
         0.20803781, -0.03102046]], shape=(3669, 100), dtype=float32)

In [32]:
len(vec[0])

100

In [33]:
model.wv.most_similar('daenerys')

[('np', 0.9975531697273254),
 ('frequency', 0.9970065355300903),
 ('matrix', 0.9968634247779846),
 ('encoder', 0.9968123435974121),
 ('px', 0.9966465830802917),
 ('onehotencoder', 0.9966080784797668),
 ('punkt', 0.9965629577636719),
 ('ea', 0.9965021014213562),
 ('name', 0.9962647557258606),
 ('docs', 0.9960742592811584)]

In [34]:
model.wv.similarity('arya','sansa')

np.float32(0.9989502)

In [35]:
model.wv.index_to_key

['the',
 'and',
 'to',
 'he',
 'of',
 'his',
 'her',
 'was',
 'you',
 'it',
 'in',
 'she',
 'that',
 'had',
 'him',
 'as',
 'with',
 'said',
 'at',
 'for',
 'not',
 'on',
 'is',
 'but',
 'from',
 'they',
 'my',
 'arya',
 'be',
 'sansa',
 'have',
 'your',
 'no',
 'all',
 'lord',
 'would',
 'so',
 'were',
 'them',
 'me',
 'when',
 'bran',
 'there',
 'ned',
 'are',
 'could',
 'ser',
 'what',
 'king',
 'metadata',
 'up',
 'will',
 'out',
 'now',
 'jon',
 'like',
 'this',
 'execution_count',
 'man',
 'if',
 'one',
 'eyes',
 'we',
 'lady',
 'back',
 'hand',
 'been',
 'do',
 'looked',
 'boy',
 'text',
 'source',
 'cell_type',
 'an',
 'only',
 'down',
 'their',
 'id',
 'see',
 'page',
 'th',
 'outputs',
 'code',
 'then',
 'here',
 'joffrey',
 'did',
 'td',
 'can',
 'or',
 'know',
 'even',
 'told',
 'before',
 'old',
 'men',
 'than',
 'dswithbappy',
 'tyrion',
 'father',
 'by',
 'face',
 'white',
 'who',
 'never',
 'watch',
 'off',
 'where',
 'into',
 'away',
 'too',
 'lannister',
 'time',
 'ov

In [36]:
from sklearn.decomposition import PCA


In [37]:
pca = PCA(n_components=3)


In [38]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [39]:
X

array([[ 0.00157362, -0.20109598, -0.0517993 ],
       [ 0.00803417, -0.15954104, -0.05415396],
       [ 0.00280029, -0.18014252, -0.07370465],
       ...,
       [-0.0144735 ,  0.21577378,  0.00149457],
       [-0.02875769,  0.25501847, -0.02395348],
       [-1.1897802 ,  0.8487223 , -0.15953891]],
      shape=(3669, 3), dtype=float32)

In [40]:
X

array([[ 0.00157362, -0.20109598, -0.0517993 ],
       [ 0.00803417, -0.15954104, -0.05415396],
       [ 0.00280029, -0.18014252, -0.07370465],
       ...,
       [-0.0144735 ,  0.21577378,  0.00149457],
       [-0.02875769,  0.25501847, -0.02395348],
       [-1.1897802 ,  0.8487223 , -0.15953891]],
      shape=(3669, 3), dtype=float32)

In [41]:
! pip install plotly

In [42]:
import plotly.express as px
fig = px.scatter_3d(x=X[:,0], y=X[:,1], z=X[:,2], text=model.wv.index_to_key)
fig.show()

In [43]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import string

# Download NLTK resource
nltk.download('punkt')
nltk.download('stopwords')

# Sample text (can be read from a file too)



[nltk_data] Downloading package punkt to /Users/al-amen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/al-
[nltk_data]     amen/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [44]:
docs = [
    "John is working on Natural Language Processing.",
    "He was running and eating at the same time.",
    "His friends were working on deep learning models."
]

In [45]:
# Preprocessing function

def preprocess(text):
    # Lower case
    text = text.lower()
    # Tokenize
    tokens = word_tokenize(text)
    # Remove punctuation and stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words and word not in string.punctuation]
    # stemming 
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(word) for word in tokens]
    return ' '.join(tokens)

# Preprocess the documents
cleaned_docs = [preprocess(doc) for doc in docs]

cleaned_docs


['john work natur languag process',
 'run eat time',
 'friend work deep learn model']

In [46]:
# Create Bag of words
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(cleaned_docs)

In [47]:
# Show vocabulary
print("Vocabulary:", vectorizer.vocabulary_)

Vocabulary: {'john': 3, 'work': 11, 'natur': 7, 'languag': 4, 'process': 8, 'run': 9, 'eat': 1, 'time': 10, 'friend': 2, 'deep': 0, 'learn': 5, 'model': 6}


In [48]:
# Show Bow matrix
print("\nBag of Words Matrix:\n", X.toarray())


Bag of Words Matrix:
 [[0 0 0 1 1 0 0 1 1 0 0 1]
 [0 1 0 0 0 0 0 0 0 1 1 0]
 [1 0 1 0 0 1 1 0 0 0 0 1]]
